### ISSUE TITLE
Question Automatic transitions after timeout

### ISSUE THREAD

**Issue by erkr** [edalquist/ha_state_machine#2]
@edalquist 

Hi Eric

Thanks for writing this very nice integration for HA. I especially like the addition of the timeout transition. So I consider to replace my current state machines with it.

Now my question, as I can't find it in the description and I can't read the Python code.

Let's presume I have a `set` transition defined to the same running state:
``` 
    "RUNNING": {
      "timeout": { "after": 120, "to": "DONE" },
      "stop": "IDLE",
      "set": "RUNNING"
    }
``` 
What happens to the timeout transition, when a set event emerges?
Will the timeout timer be reset back to 120 or will the original timer continue to count down?

I expect it will reset the timeout, as it re-enters the start, but I have to be sure 😉

Thanks
Eric

**Comment by edalquist** [comment]
It resets, I actually wasn't sure until a few days ago when I set up some lighting automations, I'm using the config below and every re-trigger of the `ON_TIMEOUT` state resets the timeout counter.

```
{
  "state": {
    "status": "OFF"
  },
  "transitions": {
    "OFF": {
      "person": "ON_TIMEOUT",
      "car": "ON_TIMEOUT",
      "arrive": "ON_TIMEOUT",
      "unlock": "ON_TIMEOUT",
      "door_open": "ON_HOLD"
    },
    "ON_HOLD": {
      "door_closed": "ON_TIMEOUT"
    },
    "ON_TIMEOUT": {
      "timeout": { "after": 300, "to": "OFF" },
      "person": "ON_TIMEOUT",
      "car": "ON_TIMEOUT",
      "arrive": "ON_TIMEOUT",
      "unlock": "ON_TIMEOUT",
      "door_open": "ON_HOLD"
    }
  }
}
```

**Comment by erkr** [comment]
I think it is worth to include this use case case in the readme

**Comment by erkr** [comment]
We can close this issue, this FR https://github.com/edalquist/ha_state_machine/issues/5#issuecomment-1745817598 covers what could be documented in the readme.
