### ISSUE TITLE
No text in the adding helper dialog

### ISSUE THREAD

**Issue by erkr** [edalquist/ha_state_machine#4]
When I add a helper, there is no text in the dialog:
![image](https://github.com/edalquist/ha_state_machine/assets/4363599/99a96ec9-fffa-4fed-91d3-a65f07d3eb31)

**Comment by edalquist** [comment]
ack, I see this as well. Something changed in Core since I last updated and I need to find time to figure out the new translations system.

**Comment by erkr** [comment]
No problem. I was able to guess the right purpose :-)

**Comment by erkr** [comment]
I have text in these dialogs since a few restarts ??? !!!
