### ISSUE TITLE
[FR] support conditional transitions.

### ISSUE THREAD

**Issue by erkr** [edalquist/ha_state_machine#6]
I made some awsome state  machines with your integration. The need for substates emerged 😎

The transitions package has support for conditional transitions. It would be great to have that exposed in this integration.
The conditional transitions in the package then have a callback. For the integration that probably becomes a little too exotic. 
My proposal is to allow for an optional condition parameter in the statemachine definition. Like this:
``` 
  "transitions": {
    "IDLE": {
      "on": "STARTING",
      "high": {"condition"="is_flammable", "to": "HEATING" },
      "high": {"condition"="not is_flammable", "to": "ALARM" },

   }
``` 
The condition `is_flammable` could be added as a boolean attribute on the state machine sensor. And you could provide a service to set / get these attributes.
Maybe a conditions section  can be aded to initialyze these attributes: 
``` 
  "state": {
    "status": "IDLE"
  },
  "conditions": {
    "is_flammable": true,
    ...

  },
  "transitions": {
    ...
```

This would add support for a kind of sub states.

Best Eric

**Comment by erkr** [comment]
Update: thinking it over; adding Boolean attributes would work but still requires a lot of plumbing in the automation. Conditions based on the state of other entities is typically needed (ideally a template expression)

Use case example is a simple motion detection:
- states: off, on, dimmed
- But the conditions are triggering only at night and only if the light was not already on when motion is detected.

Modelling that in the state machine without conditions explodes the states and the triggers in the associated automation.

The conditions in this example should just looking up the state of sun.sun and the controlled light (for the transition from off to on)

Best Eric

**Comment by edalquist** [comment]
That is getting well out of scope of my intent here, needing to read arbitrary state from HA itself is a big complexity increase. At that point I'd probably just use NodeRed which has a very good FSM with significantly more complex feature handling.
